#!/bin/bash

if [ "$1" == "average" ] ; then
	hadoop jar ./target/bd-1.0-SNAPSHOT-jar-with-dependencies.jar bd.ApacheLog /bd/apache /bd/apache_output1
	hadoop fs -cat /bd/apache_output1/*
elif [ "$1" == "inmapper" ] ; then
	hadoop jar ./target/bd-1.0-SNAPSHOT-jar-with-dependencies.jar bd.ApacheLogInMapper /bd/apache /bd/apache_output2
	hadoop fs -cat /bd/apache_output2/*
elif [ "$1" == "pair" ] ; then
	hadoop jar ./target/bd-1.0-SNAPSHOT-jar-with-dependencies.jar bd.Part2 /bd/comatrix/input /bd/comatrix/output2
	hadoop fs -cat /bd/comatrix/output2/*
elif [ "$1" == "stripe" ] ; then
	hadoop jar ./target/bd-1.0-SNAPSHOT-jar-with-dependencies.jar bd.Part3 /bd/comatrix/input /bd/comatrix/output3
	hadoop fs -cat /bd/comatrix/output3/*
elif [ "$1" == "hybrid" ] ; then
	hadoop jar ./target/bd-1.0-SNAPSHOT-jar-with-dependencies.jar bd.Part4 /bd/comatrix/input /bd/comatrix/output4
	hadoop fs -cat /bd/comatrix/output4/*
fi
