#!/bin/bash

name=mcloudera

if ! sudo docker ps --format '{{.Names}}' | grep -w $name &> /dev/null; then
    # sudo docker run -d --name $name --hostname=quickstart.cloudera --privileged=true -t -i -v ~/cloudera:/src --publish-all=true -p 8888:8888 -p 8800:80 -p 8000:7180 cloudera/quickstart /usr/bin/docker-quickstart
    sudo docker container start $name
fi

DIR="${PWD/$HOME\/cloudera/\/src}"
sudo docker exec -it -w $DIR $name bash
